/* 사용자 테이블 */
CREATE TABLE MEMBER (
	USER_ID VARCHAR2(100) NOT NULL,
	USER_NM VARCHAR2(100) NOT NULL,
	PASSWORD VARCHAR2(256) NOT NULL,
	PHONENUMBER VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	USER_TYPE VARCHAR2(10) NOT NULL,
	LAST_LOGIN date NOT NULL,
	RGISTER_DATE date NOT NULL,
    CONSTRAINT MEMBER_PK PRIMARY KEY (USER_ID)
 );


