/* 게시판 테이블 */
CREATE TABLE TEST_BOARD ( 
IDX NUMBER PRIMARY KEY, 
PARENT_IDX NUMBER, 
TITLE VARCHAR2(100) NOT NULL, 
CONTENTS VARCHAR2(4000) NOT NULL, 
HIT_CNT NUMBER NOT NULL, 
DEL_YN VARCHAR2(1) DEFAULT 'N' NOT NULL, 
CREA_DTM DATE DEFAULT SYSDATE NOT NULL, 
CREA_ID VARCHAR2(30) NOT NULL ); 

COMMENT ON TABLE TEST_BOARD IS '게시판'; 
COMMENT ON COLUMN TEST_BOARD.IDX IS '인덱스';
COMMENT ON COLUMN TEST_BOARD.PARENT_IDX IS '부모글 인덱스'; 
COMMENT ON COLUMN TEST_BOARD.TITLE IS '제목';
COMMENT ON COLUMN TEST_BOARD.CONTENTS IS '내용'; 
COMMENT ON COLUMN TEST_BOARD.HIT_CNT IS '조회수'; 
COMMENT ON COLUMN TEST_BOARD.DEL_YN IS '삭제구분'; 
COMMENT ON COLUMN TEST_BOARD.CREA_DTM IS '생성일자'; 
COMMENT ON COLUMN TEST_BOARD.CREA_ID IS '생성자 ID';


/* 게시판 시퀀스  */
CREATE SEQUENCE SEQ_TEST_BOARD_IDX
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCACHE;

